version: '3.1'
services:
  backend:
    image: backendimage:1.0.0
    build: ./backend/ 
    ports:
    - 5000:5000
    depends_on:
      - mongodb
      
    networks:
      clusternetwork:
          ipv4_address: 172.16.0.10
 
  client:
    image: clientimage:1.0.0
    build: ./client/ 
    ports:
    - 3000:3000
    networks:
       clusternetwork:
        ipv4_address: 172.16.0.11
    stdin_open: true

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    
    networks:
       clusternetwork:
        ipv4_address: 172.16.0.12    
  
networks:
  clusternetwork:
    driver: bridge


        
  

