version: '3.1'
services:
  backend:
    image: bensongathu/backendimage:1.0.0
    build: ./backend/ 
    ports:
    - 5000:5000
    depends_on:
      - mongodb
      
    networks:
      clusternetwork
  client:
    image: bensongathu/clientimage:1.0.0
    build: ./client/ 
    ports:
    - 3000:3000
    networks:
       clusternetwork
    stdin_open: true
    

  mongodb:
    image: "mongo:5.0"
    ports:
      - 27017:27017
    
    networks:
       clusternetwork 
  
networks:
  clusternetwork:
    driver: bridge


        
  

