apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: yoloDB
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yoloDB
  serviceName: yoloDB
  template:
    metadata:
      labels:
        app: yoloDB
    spec:
      containers:
        - name: yoloDB
          image: mongo:5.0.16
          env:
            - name: MONGO_DB
              value: yolomy
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: yoloData
              mountPath: /etc/data/backend
  volumeClaimTemplates:
    - metadata:
        name: yoloDatapp
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi